In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
train_data = pd.read_csv('Train_Data.csv')
test_data = pd.read_csv('Test_Data.csv')
train_data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  
0            0     0.00  
1            0     0.00  
2            0     0.00  
3            0     0.00  
4            4   925.71

In [3]:
train_data.corr()

impressions    clicks      cost  conversions   revenue
impressions     1.000000  0.987514  0.682811     0.822149  0.759671
clicks          0.987514  1.000000  0.719925     0.856941  0.798282
cost            0.682811  0.719925  1.000000     0.672202  0.581662
conversions     0.822149  0.856941  0.672202     1.000000  0.964096
revenue         0.759671  0.798282  0.581662     0.964096  1.000000

In [4]:
train_data.drop('date', axis=1, inplace=True)
train_data.drop('campaign', axis=1, inplace=True)
test_data.drop('date', axis=1, inplace=True)
test_data.drop('campaign', axis=1, inplace=True)
train_data.drop('ad', axis=1, inplace=True)
test_data.drop('ad', axis=1, inplace=True)

In [5]:
train_data.corr()

impressions    clicks      cost  conversions   revenue
impressions     1.000000  0.987514  0.682811     0.822149  0.759671
clicks          0.987514  1.000000  0.719925     0.856941  0.798282
cost            0.682811  0.719925  1.000000     0.672202  0.581662
conversions     0.822149  0.856941  0.672202     1.000000  0.964096
revenue         0.759671  0.798282  0.581662     0.964096  1.000000

In [6]:
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.head()

impressions  clicks  cost  conversions  revenue  adgroup_adgroup 1  \
0           24       6  0.08            0     0.00                  1   
1            1       0  0.00            0     0.00                  0   
2           13       4  0.04            0     0.00                  0   
3            5       4  0.08            0     0.00                  0   
4          247     126  1.29            4   925.71                  1   

   adgroup_adgroup 2  adgroup_adgroup 3  adgroup_adgroup 4  
0                  0                  0                  0  
1                  1                  0                  0  
2                  0                  1                  0  
3                  0                  0                  1  
4                  0                  0                  0

In [7]:
X_train = train_data.drop(['revenue'], axis='columns')
y_train = train_data['revenue']
X_test = test_data

In [8]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-1.29709697e-04,  6.83229814e-02,  9.22352941e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.56331069e-04,  1.24223602e-02,  2.25882353e-02, ...,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.93390982e-04,  2.82326369e-03,  5.64705882e-03, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       ...,
       [-2.65596047e-04,  1.41163185e-02,  2.07058824e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-2.90302656e-04,  5.08187465e-03,  7.52941176e-03, ...,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-2.06917851e-04,  3.78317335e-02,  5.08235294e-02, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [41]:
model = tf.keras.Sequential([
  tf.keras.layers.Dense(100, activation="relu"),
  tf.keras.layers.Dense(50, activation="relu"),
  tf.keras.layers.Dense(50, activation="relu"),
  tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile( loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(),
               metrics = tf.keras.metrics.mae)

# 3. Fit the model
model.fit(X_train, y_train, epochs= 100)

Epoch 1/100
143/143 [==============================] - 3s 10ms/step - loss: 185.0317 - mean_absolute_error: 185.0317
Epoch 2/100
143/143 [==============================] - 1s 10ms/step - loss: 164.2840 - mean_absolute_error: 164.2840
Epoch 3/100
143/143 [==============================] - 1s 10ms/step - loss: 143.8236 - mean_absolute_error: 143.8236
Epoch 4/100
143/143 [==============================] - 1s 10ms/step - loss: 120.4744 - mean_absolute_error: 120.4744
Epoch 5/100
143/143 [==============================] - 1s 10ms/step - loss: 99.5862 - mean_absolute_error: 99.5862
Epoch 6/100
143/143 [==============================] - 1s 10ms/step - loss: 82.6666 - mean_absolute_error: 82.6666
Epoch 7/100
143/143 [==============================] - 1s 10ms/step - loss: 85.0948 - mean_absolute_error: 85.0948
Epoch 8/100
143/143 [==============================] - 2s 11ms/step - loss: 75.9544 - mean_absolute_error: 75.9544
Epoch 9/100
143/143 [==============================] - 2s 11ms/step - lo

In [44]:
preds = model.predict(X_test)

In [45]:
preds = preds.astype('int64')
preds

array([[  4],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  9],
       [  0],
       [  5],
       [  0],
       [ 12],
       [  0],
       [  0],
       [ 12],
       [  0],
       [  3],
       [  0],
       [  6],
       [  0],
       [  9],
       [  0],
       [  3],
       [  0],
       [ 16],
       [  0],
       [  0],
       [ 19],
       [  6],
       [  0],
       [  0],
       [163],
       [  0],
       [100],
       [  8],
       [  8],
       [  0],
       [  5],
       [  0],
       [  0],
       [  0],
       [  0],
       [  1],
       [  0],
       [  1],
       [  2],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  1],
       [ 12],
       [  6],
       [ 37],
       [  0],
       [  0],
       [  0],
       [ 35],
       [  0],
       [  8],
       [  0],
       [ 11],
       [  0],
       [  2],
       [ 16],
       [ 11],
       [  0],
       [  0],
       [  9],
      

In [21]:
preds[preds < 50] = 0
preds

array([[  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [ 86],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [106],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
      

In [22]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('prediction1.csv', index=False)