## Rows : 55-123,141

In [7]:
import pandas as pd
import numpy as np

train_data = pd.read_csv('Train_Data.csv')
test_data = pd.read_csv('modified_test.csv')
train_data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  
0            0     0.00  
1            0     0.00  
2            0     0.00  
3            0     0.00  
4            4   925.71

In [8]:
train_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 9', 'ad 10', 'ad 11', 'ad 12', 'ad 13', 'ad 14', 'ad 15',
       'ad 16', 'ad 17', 'ad 18', 'ad 19', 'ad 20', 'ad 21', 'ad 22',
       'ad 23', 'ad 24', 'ad 25', 'ad 26', 'ad 27', 'ad 28', 'ad 29',
       'ad 30', 'ad 31', 'ad 32', 'ad 33', 'ad 34', 'ad 35', 'ad 36',
       'ad 37', 'ad 38', 'ad 39', 'ad 40', 'ad 41', 'ad 42', 'ad 43',
       'ad 44', 'ad 45', 'ad 46', 'ad 47', 'ad 48', 'ad 49', 'ad 50',
       'ad 51', 'ad 52', 'ad 53', 'ad 54', 'ad 55', 'ad 56', 'ad 57',
       'ad 58', 'ad 59', 'ad 60', 'ad 61', 'ad 62', 'ad 63', 'ad 64',
       'ad 65', 'ad 66', 'ad 67', 'ad 68', 'ad 69', 'ad 70'], dtype=object)

In [9]:
test_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 56', 'ad 55'], dtype=object)

In [10]:
train_data = train_data[train_data.ad.isin(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10','ad 56',
       'ad 55'])]

In [11]:
train_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 55', 'ad 56'], dtype=object)

In [12]:
train_data['date'] = pd.to_datetime(train_data['date'], format='%d-%m-%Y', errors='coerce')
test_data['date'] = pd.to_datetime(test_data['date'], format='%d-%m-%Y', errors='coerce')

In [13]:
train_data['date_month'] = train_data['date'].dt.month
train_data['date_day'] = train_data['date'].dt.day

test_data['date_month'] = test_data['date'].dt.month
test_data['date_day'] = test_data['date'].dt.day

In [15]:
train_data.drop('date', axis=1, inplace=True)
train_data.drop('campaign', axis=1, inplace=True)
test_data.drop('date', axis=1, inplace=True)
test_data.drop('campaign', axis=1, inplace=True)

In [16]:
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.head()

impressions  clicks  cost  conversions  revenue  date_month  date_day  \
0           24       6  0.08            0     0.00           8         1   
1            1       0  0.00            0     0.00           8         1   
2           13       4  0.04            0     0.00           8         1   
3            5       4  0.08            0     0.00           8         1   
4          247     126  1.29            4   925.71           8         1   

   adgroup_adgroup 1  adgroup_adgroup 2  adgroup_adgroup 3  ...  ad_ad 10  \
0                  1                  0                  0  ...         0   
1                  0                  1                  0  ...         0   
2                  0                  0                  1  ...         0   
3                  0                  0                  0  ...         0   
4                  1                  0                  0  ...         0   

   ad_ad 2  ad_ad 3  ad_ad 4  ad_ad 5  ad_ad 55  ad_ad 56  ad_ad 6  ad_ad 7  \
0        0        0        0        0         0         0        0        0   
1        0        0        0        0         0         0        0        0   
2        0        0        0        0         0         0        0        0   
3        0        0        0        0         0         0        0        0   
4        1        0        0        0         0         0        0        0   

   ad_ad 8  
0        0  
1        0  
2        0  
3        0  
4        0  

[5 rows x 22 columns]

In [19]:
test_data.head()

cost  impressions  clicks  conversions  date_month  date_day  \
0  0.58          121      49            1           3         1   
1  0.17           22      12            0           3         1   
2  0.05            5       3            0           3         1   
3  0.01            2       1            0           3         1   
4  0.01            3       1            0           3         1   

   adgroup_adgroup 1  adgroup_adgroup 2  adgroup_adgroup 3  adgroup_adgroup 4  \
0                  1                  0                  0                  0   
1                  0                  0                  1                  0   
2                  0                  0                  0                  1   
3                  0                  1                  0                  0   
4                  0                  1                  0                  0   

   ...  ad_ad 10  ad_ad 2  ad_ad 3  ad_ad 4  ad_ad 5  ad_ad 55  ad_ad 56  \
0  ...         0        0        0        0        0         0         0   
1  ...         0        0        0        0        0         0         0   
2  ...         0        0        0        0        0         0         0   
3  ...         0        0        0        0        0         0         0   
4  ...         0        1        0        0        0         0         0   

   ad_ad 6  ad_ad 7  ad_ad 8  
0        0        0        0  
1        0        0        0  
2        0        0        0  
3        0        0        0  
4        0        0        0  

[5 rows x 21 columns]

In [20]:
X_train = train_data.drop(['revenue'], axis='columns')
y_train = train_data['revenue']
X_test = test_data

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-0.52713638,  1.45791953,  9.04243768, ..., -0.23691184,
        -0.39692943, -0.23691184],
       [-0.5301565 , -0.1773898 ,  1.98666292, ..., -0.23691184,
        -0.39692943, -0.23691184],
       [-0.53104044, -0.45820049,  0.27039339, ..., -0.23691184,
        -0.39692943, -0.23691184],
       ...,
       [-0.53037749, -0.12783497,  1.79596631, ..., -0.23691184,
        -0.39692943, -0.23691184],
       [-0.53096678, -0.39212739,  0.46109   , ..., -0.23691184,
        -0.39692943, -0.23691184],
       [-0.52897792,  0.56593262,  4.84711215, ..., -0.23691184,
        -0.39692943, -0.23691184]])

In [22]:
import tensorflow as tf

model = tf.keras.Sequential([
  tf.keras.layers.Dense(70),
  tf.keras.layers.Dense(30),
  tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile( loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(),
               metrics = tf.keras.metrics.RootMeanSquaredError())

# 3. Fit the model
model.fit(X_train_scaled, y_train, epochs= 10)

Epoch 1/10
106/106 [==============================] - 5s 8ms/step - loss: 110.4742 - root_mean_squared_error: 306.1295
Epoch 2/10
106/106 [==============================] - 1s 5ms/step - loss: 98.7601 - root_mean_squared_error: 278.1537
Epoch 3/10
106/106 [==============================] - 1s 8ms/step - loss: 65.8963 - root_mean_squared_error: 186.9183
Epoch 4/10
106/106 [==============================] - 1s 9ms/step - loss: 55.8021 - root_mean_squared_error: 155.9637
Epoch 5/10
106/106 [==============================] - 1s 9ms/step - loss: 50.4056 - root_mean_squared_error: 147.7787
Epoch 6/10
106/106 [==============================] - 1s 9ms/step - loss: 45.9971 - root_mean_squared_error: 139.2455
Epoch 7/10
106/106 [==============================] - 1s 9ms/step - loss: 43.8790 - root_mean_squared_error: 132.0672
Epoch 8/10
106/106 [==============================] - 1s 9ms/step - loss: 43.4630 - root_mean_squared_error: 131.0100
Epoch 9/10
106/106 [==============================] - 1

In [23]:
preds = model.predict(X_test_scaled)
preds = preds.astype('int64')
preds[preds < 20] = 0
preds

array([[161],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [199],
       [  0],
       [171],
       [  0],
       [464],
       [  0],
       [  0],
       [313],
       [  0],
       [153],
       [  0],
       [176],
       [  0],
       [141],
       [  0],
       [ 26],
       [  0],
       [468],
       [  0],
       [  0],
       [602],
       [181],
       [  0],
       [  0],
       [411],
       [  0],
       [849],
       [290],
       [139],
       [  0],
       [173],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [  0],
       [436],
       [  0],
       [  0],
       [  0],
       [468],
       [  0],
       [205],
       [179],
       [  0],
       [  0],
       [  0],
       [  0],
       [719],
       [  0],
       [  0],
       [  0],
       [448],
       [145],
      

In [24]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('cleaning_1.csv', index=False)

In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('Train_Data.csv')
test_data = pd.read_csv('modified_test.csv')
train_data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  
0            0     0.00  
1            0     0.00  
2            0     0.00  
3            0     0.00  
4            4   925.71

In [3]:
train_data.drop('date', axis=1, inplace=True)
train_data.drop('campaign', axis=1, inplace=True)
test_data.drop('date', axis=1, inplace=True)
test_data.drop('campaign', axis=1, inplace=True)
train_data.drop('ad', axis=1, inplace=True)
test_data.drop('ad', axis=1, inplace=True)

In [4]:
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.head()

impressions  clicks  cost  conversions  revenue  adgroup_adgroup 1  \
0           24       6  0.08            0     0.00                  1   
1            1       0  0.00            0     0.00                  0   
2           13       4  0.04            0     0.00                  0   
3            5       4  0.08            0     0.00                  0   
4          247     126  1.29            4   925.71                  1   

   adgroup_adgroup 2  adgroup_adgroup 3  adgroup_adgroup 4  
0                  0                  0                  0  
1                  1                  0                  0  
2                  0                  1                  0  
3                  0                  0                  1  
4                  0                  0                  0

In [5]:
X_train = train_data.drop(['revenue'], axis='columns')
y_train = train_data['revenue']
X_test = test_data

In [6]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-4.62696790e-01,  8.35305552e-01,  4.60995469e+00,
         1.26529062e-01, -6.35168283e-01, -4.34886089e-01,
         1.31675802e+00, -4.80707800e-01],
       [-4.62999320e-01,  1.48430638e+00,  4.26176641e+00,
        -6.49189164e-02,  1.57438592e+00, -4.34886089e-01,
        -7.59440981e-01, -4.80707800e-01],
       [-4.66932198e-01, -3.92803699e-01,  1.38694868e-02,
        -6.49189164e-02, -6.35168283e-01, -4.34886089e-01,
        -7.59440981e-01,  2.08026581e+00],
       [-4.67033041e-01, -4.22757584e-01, -1.25405822e-01,
        -2.56366895e-01, -6.35168283e-01,  2.29945272e+00,
        -7.59440981e-01, -4.80707800e-01],
       [-4.66982619e-01, -3.72834443e-01, -1.25405822e-01,
        -2.56366895e-01,  1.57438592e+00, -4.34886089e-01,
        -7.59440981e-01, -4.80707800e-01],
       [-4.66780933e-01, -4.02788328e-01, -1.25405822e-01,
        -2.56366895e-01, -6.35168283e-01, -4.34886089e-01,
        -7.59440981e-01,  2.08026581e+00],
       [-4.56747052e-01,  2.722400

In [7]:
import tensorflow as tf

model = tf.keras.Sequential([
  tf.keras.layers.Dense(80),
  tf.keras.layers.Dense(20),
  tf.keras.layers.Dense(20),
  tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile( loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(),
               metrics = tf.keras.metrics.RootMeanSquaredError())

# 3. Fit the model
model.fit(X_train_scaled, y_train, epochs= 30)

Epoch 1/30
143/143 [==============================] - 5s 11ms/step - loss: 222.7431 - root_mean_squared_error: 1089.3541
Epoch 2/30
143/143 [==============================] - 1s 10ms/step - loss: 147.7360 - root_mean_squared_error: 723.5479
Epoch 3/30
143/143 [==============================] - 1s 10ms/step - loss: 122.1669 - root_mean_squared_error: 578.0323
Epoch 4/30
143/143 [==============================] - 1s 10ms/step - loss: 94.8569 - root_mean_squared_error: 481.7432
Epoch 5/30
143/143 [==============================] - 1s 10ms/step - loss: 78.9616 - root_mean_squared_error: 371.5063
Epoch 6/30
143/143 [==============================] - 1s 10ms/step - loss: 76.5783 - root_mean_squared_error: 353.2579
Epoch 7/30
143/143 [==============================] - 2s 11ms/step - loss: 75.6427 - root_mean_squared_error: 347.0080
Epoch 8/30
143/143 [==============================] - 1s 10ms/step - loss: 75.3935 - root_mean_squared_error: 340.6124
Epoch 9/30
143/143 [========================

In [8]:
preds = model.predict(X_test_scaled)
preds = preds.astype('int64')
preds[preds < 20] = 0
preds

array([[ 394],
       [ 236],
       [ 172],
       [   0],
       [   0],
       [   0],
       [1139],
       [   0],
       [ 386],
       [   0],
       [ 452],
       [   0],
       [  40],
       [ 612],
       [ 298],
       [   0],
       [   0],
       [ 446],
       [   0],
       [   0],
       [   0],
       [ 235],
       [ 199],
       [ 774],
       [   0],
       [  53],
       [   0],
       [ 594],
       [ 171],
       [   0],
       [ 200],
       [   0],
       [   0],
       [ 812],
       [1522],
       [   0],
       [ 389],
       [ 367],
       [ 350],
       [  20],
       [ 691],
       [ 203],
       [   0],
       [   0],
       [   0],
       [  47],
       [   0],
       [ 212],
       [   0],
       [   0],
       [ 373],
       [   0],
       [2568],
       [   0],
       [ 371],
       [   0],
       [ 215],
       [   0],
       [ 729],
       [   0],
       [ 379],
       [   0],
       [2414],
       [   0],
       [2757],
       [ 562],
       [ 2

In [9]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('cleaning_2.csv', index=False)