In [1]:
import pandas as pd
import numpy as np

In [2]:
train_data = pd.read_csv('Train_Data.csv')
test_data = pd.read_csv('Test_Data.csv')
train_data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0  01-08-2020  campaign 1  adgroup 1  ad 1           24       6  0.08   
1  01-08-2020  campaign 1  adgroup 2  ad 1            1       0  0.00   
2  01-08-2020  campaign 1  adgroup 3  ad 1           13       4  0.04   
3  01-08-2020  campaign 1  adgroup 4  ad 1            5       4  0.08   
4  01-08-2020  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  
0            0     0.00  
1            0     0.00  
2            0     0.00  
3            0     0.00  
4            4   925.71

In [3]:
train_data.date.head()

0    01-08-2020
1    01-08-2020
2    01-08-2020
3    01-08-2020
4    01-08-2020
Name: date, dtype: object

In [4]:
train_data['date'] = pd.to_datetime(train_data['date'], format='%d-%m-%Y', errors='coerce')
test_data['date'] = pd.to_datetime(test_data['date'], format='%d-%m-%Y', errors='coerce')

In [5]:
train_data.date.head()

0   2020-08-01
1   2020-08-01
2   2020-08-01
3   2020-08-01
4   2020-08-01
Name: date, dtype: datetime64[ns]

In [6]:
train_data['date_month'] = train_data['date'].dt.month
train_data['date_day'] = train_data['date'].dt.day

test_data['date_month'] = test_data['date'].dt.month
test_data['date_day'] = test_data['date'].dt.day

In [7]:
train_data.corr()

impressions    clicks      cost  conversions   revenue  \
impressions     1.000000  0.987514  0.682811     0.822149  0.759671   
clicks          0.987514  1.000000  0.719925     0.856941  0.798282   
cost            0.682811  0.719925  1.000000     0.672202  0.581662   
conversions     0.822149  0.856941  0.672202     1.000000  0.964096   
revenue         0.759671  0.798282  0.581662     0.964096  1.000000   
date_month      0.081627  0.089060  0.086645     0.051396  0.051657   
date_day        0.019950  0.017087  0.057273     0.010227 -0.004390   

             date_month  date_day  
impressions    0.081627  0.019950  
clicks         0.089060  0.017087  
cost           0.086645  0.057273  
conversions    0.051396  0.010227  
revenue        0.051657 -0.004390  
date_month     1.000000  0.008932  
date_day       0.008932  1.000000

In [8]:
train_data.head()

date    campaign    adgroup    ad  impressions  clicks  cost  \
0 2020-08-01  campaign 1  adgroup 1  ad 1           24       6  0.08   
1 2020-08-01  campaign 1  adgroup 2  ad 1            1       0  0.00   
2 2020-08-01  campaign 1  adgroup 3  ad 1           13       4  0.04   
3 2020-08-01  campaign 1  adgroup 4  ad 1            5       4  0.08   
4 2020-08-01  campaign 1  adgroup 1  ad 2          247     126  1.29   

   conversions  revenue  date_month  date_day  
0            0     0.00           8         1  
1            0     0.00           8         1  
2            0     0.00           8         1  
3            0     0.00           8         1  
4            4   925.71           8         1

In [9]:
train_data = train_data[train_data.ad.isin(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 71', 'ad 72', 'ad 73', 'ad 74', 'ad 75', 'ad 56',
       'ad 55'])]

In [10]:
train_data.drop('date', axis=1, inplace=True)
train_data.drop('campaign', axis=1, inplace=True)
test_data.drop('date', axis=1, inplace=True)
test_data.drop('campaign', axis=1, inplace=True)
train_data.drop('ad', axis=1, inplace=True)
test_data.drop('ad', axis=1, inplace=True)

In [13]:
train_data['1'] = train_data['impressions'] / train_data['clicks']
test_data['1'] = test_data['impressions'] / test_data['clicks']

train_data['2'] = train_data['impressions'] / train_data['cost']
test_data['2'] = test_data['impressions'] / test_data['cost']

In [15]:
train_data.replace([np.inf, -np.inf], np.nan, inplace=True)
test_data.replace([np.inf, -np.inf], np.nan, inplace=True)

train_data.fillna(0, inplace=True)
test_data.fillna(0, inplace=True)

In [16]:
train_data

adgroup  impressions  clicks  cost  conversions  revenue  date_month  \
0     adgroup 1           24       6  0.08            0     0.00           8   
1     adgroup 2            1       0  0.00            0     0.00           8   
2     adgroup 3           13       4  0.04            0     0.00           8   
3     adgroup 4            5       4  0.08            0     0.00           8   
4     adgroup 1          247     126  1.29            4   925.71           8   
...         ...          ...     ...   ...          ...      ...         ...   
4566  adgroup 3           19       6  0.07            0     0.00           2   
4567  adgroup 4            1       0  0.00            0     0.00           2   
4568  adgroup 3           16       8  0.12            1    93.20           2   
4569  adgroup 1           37      13  0.23            0     0.00           2   
4570  adgroup 1           19      10  0.14            0     0.00           2   

      date_day         1           2  
0            1  4.000000  300.000000  
1            1  0.000000    0.000000  
2            1  3.250000  325.000000  
3            1  1.250000   62.500000  
4            1  1.960317  191.472868  
...        ...       ...         ...  
4566        28  3.166667  271.428571  
4567        28  0.000000    0.000000  
4568        28  2.000000  133.333333  
4569        28  2.846154  160.869565  
4570        28  1.900000  135.714286  

[3387 rows x 10 columns]

In [17]:
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.head()

impressions  clicks  cost  conversions  revenue  date_month  date_day  \
0           24       6  0.08            0     0.00           8         1   
1            1       0  0.00            0     0.00           8         1   
2           13       4  0.04            0     0.00           8         1   
3            5       4  0.08            0     0.00           8         1   
4          247     126  1.29            4   925.71           8         1   

          1           2  adgroup_adgroup 1  adgroup_adgroup 2  \
0  4.000000  300.000000                  1                  0   
1  0.000000    0.000000                  0                  1   
2  3.250000  325.000000                  0                  0   
3  1.250000   62.500000                  0                  0   
4  1.960317  191.472868                  1                  0   

   adgroup_adgroup 3  adgroup_adgroup 4  
0                  0                  0  
1                  0                  0  
2                  1                  0  
3                  0                  1  
4                  0                  0

In [18]:
X_train = train_data.drop(['revenue'], axis='columns')
y_train = train_data['revenue']
X_test = test_data

In [19]:
X_train

impressions  clicks  cost  conversions  date_month  date_day         1  \
0              24       6  0.08            0           8         1  4.000000   
1               1       0  0.00            0           8         1  0.000000   
2              13       4  0.04            0           8         1  3.250000   
3               5       4  0.08            0           8         1  1.250000   
4             247     126  1.29            4           8         1  1.960317   
...           ...     ...   ...          ...         ...       ...       ...   
4566           19       6  0.07            0           2        28  3.166667   
4567            1       0  0.00            0           2        28  0.000000   
4568           16       8  0.12            1           2        28  2.000000   
4569           37      13  0.23            0           2        28  2.846154   
4570           19      10  0.14            0           2        28  1.900000   

               2  adgroup_adgroup 1  adgroup_adgroup 2  adgroup_adgroup 3  \
0     300.000000                  1                  0                  0   
1       0.000000                  0                  1                  0   
2     325.000000                  0                  0                  1   
3      62.500000                  0                  0                  0   
4     191.472868                  1                  0                  0   
...          ...                ...                ...                ...   
4566  271.428571                  0                  0                  1   
4567    0.000000                  0                  0                  0   
4568  133.333333                  0                  0                  1   
4569  160.869565                  1                  0                  0   
4570  135.714286                  1                  0                  0   

      adgroup_adgroup 4  
0                     0  
1                     0  
2                     0  
3                     1  
4                     0  
...                 ...  
4566                  0  
4567                  1  
4568                  0  
4569                  0  
4570                  0  

[3387 rows x 12 columns]

In [20]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-0.52713638,  1.45791953,  9.04243768, ..., -0.41126693,
        -0.80708709, -0.45786773],
       [-0.5301565 , -0.1773898 ,  1.98666292, ..., -0.41126693,
         1.23902366, -0.45786773],
       [-0.53104044, -0.45820049,  0.27039339, ..., -0.41126693,
        -0.80708709,  2.18403687],
       ...,
       [-0.53037749, -0.12783497,  1.79596631, ..., -0.41126693,
        -0.80708709, -0.45786773],
       [-0.53096678, -0.39212739,  0.46109   , ..., -0.41126693,
         1.23902366, -0.45786773],
       [-0.52897792,  0.56593262,  4.84711215, ..., -0.41126693,
        -0.80708709, -0.45786773]])

In [72]:
import tensorflow as tf

model = tf.keras.Sequential([
  tf.keras.layers.Dense(40),
  tf.keras.layers.Dense(40),
  tf.keras.layers.Dense(20),
  tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile( loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(),
               metrics = tf.keras.metrics.RootMeanSquaredError())

# 3. Fit the model
model.fit(X_train_scaled, y_train, epochs= 5)

Epoch 1/5
106/106 [==============================] - 3s 13ms/step - loss: 109.7511 - root_mean_squared_error: 304.2881
Epoch 2/5
106/106 [==============================] - 1s 12ms/step - loss: 73.2861 - root_mean_squared_error: 211.9761
Epoch 3/5
106/106 [==============================] - 1s 9ms/step - loss: 50.7764 - root_mean_squared_error: 146.6048
Epoch 4/5
106/106 [==============================] - 1s 9ms/step - loss: 43.9987 - root_mean_squared_error: 131.8033
Epoch 5/5
106/106 [==============================] - 1s 9ms/step - loss: 43.7046 - root_mean_squared_error: 131.8774


In [73]:
preds = model.predict(X_test_scaled)
preds = preds.astype('int64')
preds

array([[ 133],
       [   0],
       [   0],
       [   1],
       [   0],
       [   0],
       [ 132],
       [   0],
       [ 135],
       [   0],
       [ 401],
       [   0],
       [   0],
       [ 277],
       [   1],
       [ 131],
       [   0],
       [ 132],
       [   0],
       [ 139],
       [   0],
       [  -3],
       [   1],
       [ 408],
       [   0],
       [   1],
       [ 542],
       [ 137],
       [   0],
       [   1],
       [ 413],
       [   0],
       [ 830],
       [ 270],
       [ 137],
       [   0],
       [ 133],
       [  -2],
       [   0],
       [   0],
       [   0],
       [  -2],
       [   1],
       [   0],
       [  -2],
       [   0],
       [   0],
       [   0],
       [   0],
       [  -2],
       [   1],
       [   0],
       [   0],
       [ 277],
       [ 127],
       [ 138],
       [   1],
       [  -2],
       [  -1],
       [ 822],
       [   0],
       [ 271],
       [   0],
       [ 266],
       [   1],
       [  -1],
       [ 4

In [74]:
preds[preds < 20] = 0
preds

array([[ 133],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 132],
       [   0],
       [ 135],
       [   0],
       [ 401],
       [   0],
       [   0],
       [ 277],
       [   0],
       [ 131],
       [   0],
       [ 132],
       [   0],
       [ 139],
       [   0],
       [   0],
       [   0],
       [ 408],
       [   0],
       [   0],
       [ 542],
       [ 137],
       [   0],
       [   0],
       [ 413],
       [   0],
       [ 830],
       [ 270],
       [ 137],
       [   0],
       [ 133],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 277],
       [ 127],
       [ 138],
       [   0],
       [   0],
       [   0],
       [ 822],
       [   0],
       [ 271],
       [   0],
       [ 266],
       [   0],
       [   0],
       [ 4

In [66]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('datetime.csv', index=False)