In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv('Train_Data.csv')
test_data = pd.read_csv('Test_Data.csv')

In [3]:
train_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 9', 'ad 10', 'ad 11', 'ad 12', 'ad 13', 'ad 14', 'ad 15',
       'ad 16', 'ad 17', 'ad 18', 'ad 19', 'ad 20', 'ad 21', 'ad 22',
       'ad 23', 'ad 24', 'ad 25', 'ad 26', 'ad 27', 'ad 28', 'ad 29',
       'ad 30', 'ad 31', 'ad 32', 'ad 33', 'ad 34', 'ad 35', 'ad 36',
       'ad 37', 'ad 38', 'ad 39', 'ad 40', 'ad 41', 'ad 42', 'ad 43',
       'ad 44', 'ad 45', 'ad 46', 'ad 47', 'ad 48', 'ad 49', 'ad 50',
       'ad 51', 'ad 52', 'ad 53', 'ad 54', 'ad 55', 'ad 56', 'ad 57',
       'ad 58', 'ad 59', 'ad 60', 'ad 61', 'ad 62', 'ad 63', 'ad 64',
       'ad 65', 'ad 66', 'ad 67', 'ad 68', 'ad 69', 'ad 70'], dtype=object)

In [4]:
test_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 71', 'ad 72', 'ad 73', 'ad 74', 'ad 75', 'ad 56',
       'ad 55'], dtype=object)

In [5]:
train_data = train_data[train_data.ad.isin(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 71', 'ad 72', 'ad 73', 'ad 74', 'ad 75', 'ad 56',
       'ad 55'])]

In [6]:
train_data

date    campaign    adgroup     ad  impressions  clicks  cost  \
0     01-08-2020  campaign 1  adgroup 1   ad 1           24       6  0.08   
1     01-08-2020  campaign 1  adgroup 2   ad 1            1       0  0.00   
2     01-08-2020  campaign 1  adgroup 3   ad 1           13       4  0.04   
3     01-08-2020  campaign 1  adgroup 4   ad 1            5       4  0.08   
4     01-08-2020  campaign 1  adgroup 1   ad 2          247     126  1.29   
...          ...         ...        ...    ...          ...     ...   ...   
4566  28-02-2021  campaign 1  adgroup 3  ad 55           19       6  0.07   
4567  28-02-2021  campaign 1  adgroup 4  ad 55            1       0  0.00   
4568  28-02-2021  campaign 1  adgroup 3  ad 56           16       8  0.12   
4569  28-02-2021  campaign 1  adgroup 1  ad 56           37      13  0.23   
4570  28-02-2021  campaign 1  adgroup 1  ad 55           19      10  0.14   

      conversions  revenue  
0               0     0.00  
1               0     0.00  
2               0     0.00  
3               0     0.00  
4               4   925.71  
...           ...      ...  
4566            0     0.00  
4567            0     0.00  
4568            1    93.20  
4569            0     0.00  
4570            0     0.00  

[3387 rows x 9 columns]

In [7]:
train_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 55', 'ad 56'], dtype=object)

In [8]:
train_data.drop('date', axis=1, inplace=True)
train_data.drop('campaign', axis=1, inplace=True)
test_data.drop('date', axis=1, inplace=True)
test_data.drop('campaign', axis=1, inplace=True)
train_data.drop('ad', axis=1, inplace=True)
test_data.drop('ad', axis=1, inplace=True)

In [9]:
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.head()

impressions  clicks  cost  conversions  revenue  adgroup_adgroup 1  \
0           24       6  0.08            0     0.00                  1   
1            1       0  0.00            0     0.00                  0   
2           13       4  0.04            0     0.00                  0   
3            5       4  0.08            0     0.00                  0   
4          247     126  1.29            4   925.71                  1   

   adgroup_adgroup 2  adgroup_adgroup 3  adgroup_adgroup 4  
0                  0                  0                  0  
1                  1                  0                  0  
2                  0                  1                  0  
3                  0                  0                  1  
4                  0                  0                  0

In [10]:
X_train = train_data.drop(['revenue'], axis='columns')
y_train = train_data['revenue']
X_test = test_data

In [11]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-4.40713536e-04,  2.80742459e-01,  4.67245161e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-8.70933893e-04,  5.10440835e-02,  1.14427386e-01, ...,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-9.96852046e-04,  1.16009281e-02,  2.86068466e-02, ...,
         0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
       ...,
       [-9.02413431e-04,  5.80046404e-02,  1.04891771e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [-9.86358867e-04,  2.08816705e-02,  3.81424621e-02, ...,
         0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [-7.03043022e-04,  1.55452436e-01,  2.57461619e-01, ...,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [48]:
from sklearn.model_selection import RandomizedSearchCV
# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 10, stop = 300, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(5, 50, num = 6)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5,6,7, 8,9,10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4, 5, 6]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
print(random_grid)

{'n_estimators': [10, 42, 74, 106, 138, 171, 203, 235, 267, 300], 'max_features': ['auto', 'sqrt'], 'max_depth': [5, 14, 23, 32, 41, 50, None], 'min_samples_split': [2, 5, 6, 7, 8, 9, 10], 'min_samples_leaf': [1, 2, 4, 5, 6], 'bootstrap': [True, False]}


In [49]:
rf = RandomForestRegressor()
# Random search of parameters, using 3 fold cross validation, 
# search across 100 different combinations, and use all available cores
rf_random = RandomizedSearchCV(estimator = rf, param_distributions = random_grid, n_iter = 10, cv = 3, verbose=2, random_state=42, n_jobs = -1)
# Fit the random search model
rf_random.fit(X_train_scaled, y_train)

Fitting 3 folds for each of 10 candidates, totalling 30 fits


RandomizedSearchCV(cv=3, estimator=RandomForestRegressor(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [5, 14, 23, 32, 41, 50,
                                                      None],
                                        'max_features': ['auto', 'sqrt'],
                                        'min_samples_leaf': [1, 2, 4, 5, 6],
                                        'min_samples_split': [2, 5, 6, 7, 8, 9,
                                                              10],
                                        'n_estimators': [10, 42, 74, 106, 138,
                                                         171, 203, 235, 267,
                                                         300]},
                   random_state=42, verbose=2)

In [50]:
rf_random.best_params_

{'n_estimators': 203,
 'min_samples_split': 5,
 'min_samples_leaf': 5,
 'max_features': 'auto',
 'max_depth': None,
 'bootstrap': True}

In [64]:
from sklearn.ensemble import RandomForestRegressor

rf_tuned = RandomForestRegressor(n_estimators= 100,
                                min_samples_split= 5,
                                min_samples_leaf= 5,
                                max_features= 'auto',
                                max_depth= 4,
                                bootstrap= True)
rf_tuned.fit(X_train_scaled, y_train)

RandomForestRegressor(max_depth=4, min_samples_leaf=5, min_samples_split=5)

In [65]:
preds = rf_tuned.predict(X_test_scaled)
preds = preds.astype('int64')
preds

array([ 154,    0,    0,    0,    0,    0,  181,    0,  180,    0,  453,
          0,    0,  350,    0,  152,    0,  180,    0,  143,    0,    0,
          0,  453,    0,    0,  599,  180,    0,    0,  421,    0, 1035,
        342,  143,    0,  180,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,  352,  181,
        144,    0,    0,    0,  923,    0,  350,    0,  352,    0,    0,
        454,  181,    0,    0,  354,    0,    0,    0,  181,  143,  599,
          0,    0,    0,  453,  146,    0,  143,    0,    0,  599, 1016,
          0,  350,  343,  318,    0,  660,  143,    0,    0,    0,    0,
          0,  154,    0,    0,  180,    0, 1783,    0,  343,    0,  164,
          0,  605,    0,  342,    0, 1783,    0, 1783,  453,  143,    0,
          0,  453,    0,    0,    0,  453,    0,  181,  180,    0,    0,
          0,    0,  727,    0,    0,    0,  453,    0,  144,    0,    0,
          0,  144,    0,    0,  343,  439,    0,   

In [66]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('prediction4.csv', index=False)

In [23]:
import tensorflow as tf

model = tf.keras.Sequential([
  tf.keras.layers.Dense(100),
  tf.keras.layers.Dense(20),
  tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile( loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(learning_rate=0.005),
               metrics = tf.keras.metrics.RootMeanSquaredError())

# 3. Fit the model
model.fit(X_train_scaled, y_train, epochs= 10)

Epoch 1/10
106/106 [==============================] - 2s 11ms/step - loss: 102.2771 - root_mean_squared_error: 286.3014
Epoch 2/10
106/106 [==============================] - 1s 11ms/step - loss: 65.1308 - root_mean_squared_error: 172.8205
Epoch 3/10
106/106 [==============================] - 1s 10ms/step - loss: 53.1951 - root_mean_squared_error: 148.8810
Epoch 4/10
106/106 [==============================] - 1s 11ms/step - loss: 45.2056 - root_mean_squared_error: 134.1573
Epoch 5/10
106/106 [==============================] - 1s 10ms/step - loss: 44.2342 - root_mean_squared_error: 130.5198
Epoch 6/10
106/106 [==============================] - 1s 10ms/step - loss: 44.2490 - root_mean_squared_error: 131.0140
Epoch 7/10
106/106 [==============================] - 1s 11ms/step - loss: 44.1840 - root_mean_squared_error: 131.1639
Epoch 8/10
106/106 [==============================] - 1s 11ms/step - loss: 43.9312 - root_mean_squared_error: 131.8784
Epoch 9/10
106/106 [===========================

In [24]:
preds = model.predict(X_test_scaled)
preds = preds.astype('int64')
preds

array([[ 152],
       [   2],
       [   0],
       [   2],
       [   2],
       [   0],
       [ 169],
       [   2],
       [ 151],
       [   0],
       [ 436],
       [   2],
       [   1],
       [ 287],
       [   2],
       [ 148],
       [   2],
       [ 153],
       [   8],
       [ 138],
       [   0],
       [  17],
       [   2],
       [ 438],
       [   0],
       [   2],
       [ 573],
       [ 156],
       [   0],
       [   2],
       [ 407],
       [   1],
       [ 826],
       [ 284],
       [ 137],
       [   2],
       [ 152],
       [   8],
       [   0],
       [   0],
       [   7],
       [   9],
       [   2],
       [   4],
       [  12],
       [   0],
       [   0],
       [   0],
       [   2],
       [   7],
       [   2],
       [   1],
       [   4],
       [ 284],
       [ 157],
       [ 134],
       [   2],
       [   5],
       [   0],
       [ 841],
       [   2],
       [ 287],
       [   0],
       [ 305],
       [   3],
       [   9],
       [ 4

In [25]:
preds[preds < 20] = 0
preds

array([[ 152],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 169],
       [   0],
       [ 151],
       [   0],
       [ 436],
       [   0],
       [   0],
       [ 287],
       [   0],
       [ 148],
       [   0],
       [ 153],
       [   0],
       [ 138],
       [   0],
       [   0],
       [   0],
       [ 438],
       [   0],
       [   0],
       [ 573],
       [ 156],
       [   0],
       [   0],
       [ 407],
       [   0],
       [ 826],
       [ 284],
       [ 137],
       [   0],
       [ 152],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 284],
       [ 157],
       [ 134],
       [   0],
       [   0],
       [   0],
       [ 841],
       [   0],
       [ 287],
       [   0],
       [ 305],
       [   0],
       [   0],
       [ 4

In [26]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('prediction1.csv', index=False)