In [1]:
import numpy as np
import pandas as pd

In [2]:
train_data = pd.read_csv('Train_Data.csv')
test_data = pd.read_csv('Test_Data.csv')

In [3]:
train_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 9', 'ad 10', 'ad 11', 'ad 12', 'ad 13', 'ad 14', 'ad 15',
       'ad 16', 'ad 17', 'ad 18', 'ad 19', 'ad 20', 'ad 21', 'ad 22',
       'ad 23', 'ad 24', 'ad 25', 'ad 26', 'ad 27', 'ad 28', 'ad 29',
       'ad 30', 'ad 31', 'ad 32', 'ad 33', 'ad 34', 'ad 35', 'ad 36',
       'ad 37', 'ad 38', 'ad 39', 'ad 40', 'ad 41', 'ad 42', 'ad 43',
       'ad 44', 'ad 45', 'ad 46', 'ad 47', 'ad 48', 'ad 49', 'ad 50',
       'ad 51', 'ad 52', 'ad 53', 'ad 54', 'ad 55', 'ad 56', 'ad 57',
       'ad 58', 'ad 59', 'ad 60', 'ad 61', 'ad 62', 'ad 63', 'ad 64',
       'ad 65', 'ad 66', 'ad 67', 'ad 68', 'ad 69', 'ad 70'], dtype=object)

In [4]:
test_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 71', 'ad 72', 'ad 73', 'ad 74', 'ad 75', 'ad 56',
       'ad 55'], dtype=object)

In [5]:
train_data = train_data[train_data.ad.isin(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 71', 'ad 72', 'ad 73', 'ad 74', 'ad 75', 'ad 56',
       'ad 55'])]

In [6]:
train_data

date    campaign    adgroup     ad  impressions  clicks  cost  \
0     01-08-2020  campaign 1  adgroup 1   ad 1           24       6  0.08   
1     01-08-2020  campaign 1  adgroup 2   ad 1            1       0  0.00   
2     01-08-2020  campaign 1  adgroup 3   ad 1           13       4  0.04   
3     01-08-2020  campaign 1  adgroup 4   ad 1            5       4  0.08   
4     01-08-2020  campaign 1  adgroup 1   ad 2          247     126  1.29   
...          ...         ...        ...    ...          ...     ...   ...   
4566  28-02-2021  campaign 1  adgroup 3  ad 55           19       6  0.07   
4567  28-02-2021  campaign 1  adgroup 4  ad 55            1       0  0.00   
4568  28-02-2021  campaign 1  adgroup 3  ad 56           16       8  0.12   
4569  28-02-2021  campaign 1  adgroup 1  ad 56           37      13  0.23   
4570  28-02-2021  campaign 1  adgroup 1  ad 55           19      10  0.14   

      conversions  revenue  
0               0     0.00  
1               0     0.00  
2               0     0.00  
3               0     0.00  
4               4   925.71  
...           ...      ...  
4566            0     0.00  
4567            0     0.00  
4568            1    93.20  
4569            0     0.00  
4570            0     0.00  

[3387 rows x 9 columns]

In [7]:
train_data['ad'].unique()

array(['ad 1', 'ad 2', 'ad 3', 'ad 4', 'ad 5', 'ad 6', 'ad 7', 'ad 8',
       'ad 10', 'ad 55', 'ad 56'], dtype=object)

In [8]:
train_data.drop('date', axis=1, inplace=True)
train_data.drop('campaign', axis=1, inplace=True)
test_data.drop('date', axis=1, inplace=True)
test_data.drop('campaign', axis=1, inplace=True)
train_data.drop('ad', axis=1, inplace=True)
test_data.drop('ad', axis=1, inplace=True)

In [9]:
train_data = pd.get_dummies(train_data)
test_data = pd.get_dummies(test_data)
train_data.head()

impressions  clicks  cost  conversions  revenue  adgroup_adgroup 1  \
0           24       6  0.08            0     0.00                  1   
1            1       0  0.00            0     0.00                  0   
2           13       4  0.04            0     0.00                  0   
3            5       4  0.08            0     0.00                  0   
4          247     126  1.29            4   925.71                  1   

   adgroup_adgroup 2  adgroup_adgroup 3  adgroup_adgroup 4  
0                  0                  0                  0  
1                  1                  0                  0  
2                  0                  1                  0  
3                  0                  0                  1  
4                  0                  0                  0

In [10]:
X_train = train_data.drop(['revenue'], axis='columns')
y_train = train_data['revenue']
X_test = test_data

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_train_scaled

X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[-0.52713638,  1.45791953,  9.04243768, ..., -0.41126693,
        -0.80708709, -0.45786773],
       [-0.5301565 , -0.1773898 ,  1.98666292, ..., -0.41126693,
         1.23902366, -0.45786773],
       [-0.53104044, -0.45820049,  0.27039339, ..., -0.41126693,
        -0.80708709,  2.18403687],
       ...,
       [-0.53037749, -0.12783497,  1.79596631, ..., -0.41126693,
        -0.80708709, -0.45786773],
       [-0.53096678, -0.39212739,  0.46109   , ..., -0.41126693,
         1.23902366, -0.45786773],
       [-0.52897792,  0.56593262,  4.84711215, ..., -0.41126693,
        -0.80708709, -0.45786773]])

In [19]:
from sklearn.ensemble import RandomForestRegressor

rf_tuned = RandomForestRegressor(n_estimators= 300,
                                min_samples_split= 5,
                                min_samples_leaf= 4,
                                max_features= 'auto',
                                max_depth= 20,
                                bootstrap= True)
rf_tuned.fit(X_train_scaled, y_train)

RandomForestRegressor(max_depth=20, min_samples_leaf=4, min_samples_split=5,
                      n_estimators=300)

In [20]:
preds = rf_tuned.predict(X_test_scaled)
preds = preds.astype('int64')
preds

array([ 168,    0,    0,    0,    0,    0,  161,    0,  165,    0,  547,
          0,    0,  416,    0,  178,    0,  160,    0,  185,    0,    0,
          0,  547,    0,    0,  677,  160,    0,    0,  499,    0, 1088,
        426,  171,    0,  160,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,  428,  161,
        150,    0,    0,    0,  977,    0,  427,    0,  406,    0,    0,
        544,  161,    0,    0,  399,    0,    0,    0,  164,  188,  636,
          0,    0,    0,  540,  177,    0,  184,    0,    0,  674, 1104,
          0,  426,  419,  260,    0,  683,  183,    0,    0,    0,    0,
          0,  172,    0,    0,  160,    0, 1828,    0,  421,    0,  163,
          0,  681,    0,  427,    0, 1828,    0, 1828,  564,  183,    0,
          0,  544,    0,    0,    0,  540,    0,  161,  160,    0,    0,
          0,    0,  842,    0,    0,    0,  550,    0,  184,    0,    0,
          0,  183,    0,    0,  447,  536,    0,   

In [21]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('prediction4.csv', index=False)

In [62]:
import tensorflow as tf

model = tf.keras.Sequential([
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(10),
  tf.keras.layers.Dense(1),
])

# 2. Compile the model
model.compile( loss = tf.keras.losses.mae,
               optimizer = tf.keras.optimizers.Adam(),
               metrics = tf.keras.metrics.RootMeanSquaredError())

# 3. Fit the model
model.fit(X_train_scaled, y_train, epochs= 10)

Epoch 1/10
106/106 [==============================] - 3s 11ms/step - loss: 111.4008 - root_mean_squared_error: 308.1666
Epoch 2/10
106/106 [==============================] - 1s 10ms/step - loss: 106.1904 - root_mean_squared_error: 294.9646
Epoch 3/10
106/106 [==============================] - 1s 10ms/step - loss: 68.1636 - root_mean_squared_error: 191.8641
Epoch 4/10
106/106 [==============================] - 1s 11ms/step - loss: 53.4681 - root_mean_squared_error: 148.3834
Epoch 5/10
106/106 [==============================] - 1s 10ms/step - loss: 46.0667 - root_mean_squared_error: 138.1635
Epoch 6/10
106/106 [==============================] - 1s 10ms/step - loss: 43.1352 - root_mean_squared_error: 131.5572
Epoch 7/10
106/106 [==============================] - 1s 11ms/step - loss: 43.1314 - root_mean_squared_error: 130.7568
Epoch 8/10
106/106 [==============================] - 1s 10ms/step - loss: 42.9633 - root_mean_squared_error: 130.2342
Epoch 9/10
106/106 [==========================

In [63]:
preds = model.predict(X_test_scaled)
preds = preds.astype('int64')
preds

array([[ 140],
       [   3],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 160],
       [   0],
       [ 146],
       [   1],
       [ 410],
       [   3],
       [   1],
       [ 273],
       [   0],
       [ 135],
       [   3],
       [ 148],
       [   3],
       [ 130],
       [   0],
       [  13],
       [   0],
       [ 413],
       [   0],
       [   0],
       [ 538],
       [ 152],
       [   1],
       [   0],
       [ 382],
       [   1],
       [ 778],
       [ 263],
       [ 128],
       [   0],
       [ 147],
       [   2],
       [   0],
       [   1],
       [   1],
       [   4],
       [   0],
       [   5],
       [   7],
       [   0],
       [   0],
       [   0],
       [   3],
       [   1],
       [   0],
       [   1],
       [   6],
       [ 270],
       [ 145],
       [ 126],
       [   0],
       [   0],
       [   0],
       [ 795],
       [   0],
       [ 267],
       [   0],
       [ 288],
       [   0],
       [  11],
       [ 4

In [64]:
preds[preds < 10] = 0
preds

array([[ 140],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 160],
       [   0],
       [ 146],
       [   0],
       [ 410],
       [   0],
       [   0],
       [ 273],
       [   0],
       [ 135],
       [   0],
       [ 148],
       [   0],
       [ 130],
       [   0],
       [  13],
       [   0],
       [ 413],
       [   0],
       [   0],
       [ 538],
       [ 152],
       [   0],
       [   0],
       [ 382],
       [   0],
       [ 778],
       [ 263],
       [ 128],
       [   0],
       [ 147],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [   0],
       [ 270],
       [ 145],
       [ 126],
       [   0],
       [   0],
       [   0],
       [ 795],
       [   0],
       [ 267],
       [   0],
       [ 288],
       [   0],
       [  11],
       [ 4

In [65]:
prediction = pd.DataFrame(preds, columns=['revenue']).to_csv('prediction1.csv', index=False)